### ISSUE TITLE
Error in constructor of X509

### ISSUE THREAD

**Issue by yhojann-cl** [ndparker/dotfiles#1]
In `dotfiles/bin/lineage-verify.py ` line 23, change:

```python
pycert = X509.__new__(X509)
```

By:

```python
pycert = X509()
```

The `__new__` magic function can not call the self objects declared on the `__init__`:

>  File "/home/user/.local/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1449, in get_issuer
>    self._issuer_invalidator.add(name)
> AttributeError: 'X509' object has no attribute '_issuer_invalidator'

The `_issuer_invalidator` is declared on the `__init__`.

**Comment by ndparker** [comment]
Thank you. In the meantime I've changed the whole implementation to the official one :-)
